version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd frontend
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  base-directory: frontend/public
  files:
    - "**/*"

cache:
  paths:
    - "frontend/node_modules/**/*"
